runtime: go119
api_version: go1
jwt_secret: "devtimego"

handlers:
- url: /.*
  script: _go_app

database:
  host: 192.168.244.140
  port: 3306
  username: root
  password: root
  dbName: devtimego

redis:
  host: 192.168.244.140
  port: 6379
  password: redis
  db: 0
  taskDb: 1 # Recommend to use a different db for task
