runtime: go119
api_version: go1

handlers:
- url: /.*
  script: _go_app

database:
  host: 192.168.1.19
  port: 3306
  username: root
  password: root
  dbName: wakatimekt

redis:
  host: 192.168.244.140
  port: 6379
  password: redis
  db: 0